sudo: required

services:
- docker

archlinux:
  repos:
  - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
  # pacman packages
  - python
  - perl
  # aur packages
  - go-git
  # packages from papyros repo
  - papyros-shell
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
  - "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"
  script:
  - ls -l

script:
- "curl -s https://raw.githubusercontent.com/alxhoff/arch-travis/master/arch-travis.sh | bash"